export const BLOG_LIST_REQUEST = 'BLOG_LIST_REQUEST'
export const BLOG_LIST_SUCCESS = 'BLOG_LIST_SUCCESS'
export const BLOG_LIST_FAIL = 'BLOG_LIST_FAIL'

export const BLOG_SELECT_REQUEST = 'BLOG_SELECT_REQUEST'
export const BLOG_SELECT_SUCCESS = 'BLOG_SELECT_SUCCESS'
export const BLOG_SELECT_FAIL = 'BLOG_SELECT_FAIL'

export const BLOG_SELECT_CLEAR = 'BLOG_SELECT_CLEAR'
